### PR TITLE
Port the project to CMake meta-build system

### PR DESCRIPTION
**Pull request by gikari**
This is my attempt to port RCS Server to CMake as was proposed in #31. It's a little bit messy due to unusual project structure and some legacy macros (such as `HAVE_SSTREAM`). I hope I didn't forget anything. Please check it, because I am not very familiar with GNU Make and may miss some necessary steps. 

## Testing

Assuming you're in project's source directory, run:
```
mkdir build; cd build
cmake -G Ninja ..
cmake --build .
```
You can omit the `-G Ninja` if you want to use default generator.

### CODE REVIEW

**Comment by herodrigues** [comment]
Have you tested it?

**Comment by gikari** [comment]
> Have you tested it?

I build it. It builds. 

```
mkdir build; cd build;
cmake -G Ninja ..
cmkae --build .
```

Run the server, does not have any problems at the first glance. What else should I test?

**Comment by herodrigues** [comment]
That should be fine.
Unless there's any error while running some matches.

**Comment by hidehisaakiyama** [comment]
Thanks for your contribution. I have just downloaded and tried to build your source tree.
Two quick comments:

1. It seems your changes require CMake 3.10 or higher.
Because the default version of CMake on Ubuntu 16.04 is still 3.5.1, we should support the older version CMake.

2. Please do not remove Autotools settings yet. 
I hope we will move to CMake. However, we still need time for migration.

I will check deeply later :)

**Comment by gikari** [comment]
>     2. Please do not remove Autotools settings yet.
>        I hope we will move to CMake. However, we still need time for migration.

Does it mean you are going to support two build system generators at once? Isn't it redundant and inconvenient? Or do you plan to remove autotools in the future? What do you mean by "migration" exactly? Is it about CI?

**Comment by herodrigues** [comment]
@gikari It's not redundant. We cannot drop the autotools right away.
There might be several users that have written scripts using the current build environment.

I think we can add CMake as an alternative build option for now.

**Comment by gikari** [comment]
> The library version does not matched with the version built by autotools. Please check the version number strings.

Which library do you mean exactly?

**Comment by hidehisaakiyama** [comment]
> > The library version does not matched with the version built by autotools. Please check the version number strings.
> 
> Which library do you mean exactly? What version was expected?

We can confirm the version of shared libraries in the installed directory.
The versions of the latest release are as follows:
```
librcssclangparser.so.2.1.0
librcssconfparser.so.3.0.0
librcssgz.so.1.0.0
librcssnet.so.1.0.1
```

The versions in your branch are:
```
librcssclangparser.so.3.0.1
librcssconfparser.so.3.0.0
librcssgz.so.1.0.0
librcssnet.so.1.1.0

```

**Comment by gikari** [comment]
Friendly ping :)

**Comment by patrickelectric** [comment]
can this be merged ? @hidehisaakiyama @herodrigues

**Comment by hidehisaakiyama** [comment]
Sorry for my late response.
Unfortunately, I don't have enough time to check the code but will try it in the next few weeks.

**Comment by patrickelectric** [comment]
I did the test and it works, the only thing that is missing is the include of the boost library, but we can do that after merged since this PR already accomplish a good work and can be improved later

**Comment by gikari** [comment]
> I did the test and it works, the only thing that is missing is the include of the boost library, but we can do that after merged since this PR already accomplish a good work and can be improved later

What do you mean by "include of the boost library"? It finds the Boost filesystem with `find_package` and links with it with `target_link_libraries`. What else should be done? Am I missing something?

**Comment by patrickelectric** [comment]
> > I did the test and it works, the only thing that is missing is the include of the boost library, but we can do that after merged since this PR already accomplish a good work and can be improved later
> 
> What do you mean by "include of the boost library"? It finds the Boost filesystem with `find_package` and links with it with `target_link_libraries`. What else should be done? Am I missing something?

It misses the line `include_directories(${Boost_INCLUDE_DIR})`, for the compiler to find the header files. This is not necessary for OSs such as linux where the include files location is well defined, but for macOS is necessary :) But as I said, that should not hold the PR.

**Comment by gikari** [comment]
> It misses the line `include_directories(${Boost_INCLUDE_DIR})`, for the compiler to find the header files. This is not necessary for OSs such as linux where the include files location is well defined, but for macOS is necessary :) But as I said, that should not hold the PR.

I don't have a Mac to test, so if you want, you can make a PR, when this gets merged. :) However, I would use `target_include_directories` instead of `include_directories`.

**Comment by patrickelectric** [comment]
> > It misses the line `include_directories(${Boost_INCLUDE_DIR})`, for the compiler to find the header files. This is not necessary for OSs such as linux where the include files location is well defined, but for macOS is necessary :) But as I said, that should not hold the PR.
> 
> I don't have a Mac to test, so if you want, you can make a PR, when this gets merged. :) However, I would use `target_include_directories` instead of `include_directories`.

Totally agree, no problem. I just want to see this PR merged asap

**Comment by gikari** [comment]
@patrickelectric According to [FindBoost documentation](https://cmake.org/cmake/help/v3.5/module/FindBoost.html), linking to `Boost::boost` (`Boost::header` in newer CMake versions) should propagate include directories to the users of this target. If you can, you may want to test this change in macOS.

**Comment by patrickelectric** [comment]
@hidehisaakiyama  can we have this merged ?

**Comment by hidehisaakiyama** [comment]
> @hidehisaakiyama can we have this merged ?

I'm sorry. I'm too busy now, but I may try to check this week.

**Comment by herodrigues** [comment]
I can left a review on this PR this week. What I wanted to do first is to create GitHub actions for both make and cmake.

**Comment by herodrigues** [comment]
While this PR is not approved, you're free to make a fork of this repo and use it on your end.
But this a opensource project used by several developers and we need to make sure it's working for everyone.

**Comment by tahaeghtesad** [comment]
@gikari I just cloned your CMake version and compiled/installed with the following commands:

`mkdir build; cd build
cmake -G Ninja ..
cmake --build .
cmake --install . --prefix <>`

However, when I try to run the server, it exits with this error:

`rcssserver: error while loading shared libraries: librcssclangparser.so.2: cannot open shared object file: No such file or directory`

Do you happen to know what is the problem that the `rcssclangparser` does not compile?

**Comment by hidehisaakiyama** [comment]
Sorry for the too late response.
I have merged your changes to the develop branch with small fixes.
If you find any issues, please post a new issue or send another pull request.
Thanks for your contributions.

**Pull request closed without merging**
