### PR TITLE
Add Dockerfile and update README.md

### PR DESCRIPTION
**Pull request by heitorrapela**
Add Dockerfile to Ubuntu 12, libs to link inside container and update README.md.

### CODE REVIEW

**Comment by herodrigues** [comment]
@heitorrapela Could you please resolve all conflicts and update this PR?

**Comment by heitorrapela** [comment]
Hello @herodrigues , I think that i have resolve all conflicts. Could you check it? Thanks.
Best Regards,

**Comment by herodrigues** [comment]
@heitorrapela can you add the dockerfile as a status check to your fork so you can use it to protect the master branch?

**Comment by heitorrapela** [comment]
I tried, but i never had done that, if you could clarify it :)
I put on my fork the status check, it is ok now? Or I have to recreate fork and put status before open pr?

**Comment by herodrigues** [comment]
- Fork rcssserver again. 
- Lock your fork's `master` branch and put your changes in another branch, let's say `dev` branch.
- Open a PR from `dev` to `master`. A new status check for the dockerfile should appear on your PR.
- Go to settings and mark the status check as required.
- If the status check is succesful, you can try opening the same PR here

**Comment by heitorrapela** [comment]
@herodrigues Thanks, I will do it soon.

**Comment by herodrigues** [comment]
@heitorrapela I just noticed the build step has some extra commands that are not necessary. Also, only a few libraries are needed to install the server.

You gonna go with CircleCI only. 
It's easy for users to check their contributions meet the requirements.

Thanks anyway :+1:

**Pull request closed without merging**
